# Generated by Django 3.2.6 on 2023-09-06 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='delete_at',
            new_name='deleted_at',
        ),
    ]
